version: '3.8'

services:
  app:
    build: .
    container_name: ngticket-front
    ports:
      - "${APP_PORT}:3000"
    networks:
      - app_network
    restart: unless-stopped

networks:
  app_network:
    driver: bridge
    ipam:
      config:
        - subnet: ${APP_SUBNET}
          gateway: ${APP_GATEWAY}
